Repository jenkinsci/config-file-provider-plugin, pull requests merged in 2022-02, with the labels that each got.

#175 Enable gitpod support
  .gitpod.yml
Labels: chore

#145 JENKINS-60498 reconcile configs collection type when set by CasC
  src/main/java/org/jenkinsci/plugins/configfiles/GlobalConfigFiles.java
  src/test/java/org/jenkinsci/plugins/configfiles/GlobalConfigFilesConfigAsCodeTest.java
Labels: bugfix

#160 Modernise forms
  src/main/resources/lib/configfiles/selectprovider.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/edit.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/selectprovider.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/selectprovider.properties
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/show.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/custom/security/CustomizedCredentialMapping/config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/maven/GlobalMavenSettingsConfig/edit-config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/maven/GlobalMavenSettingsConfig/show-config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/maven/MavenSettingsConfig/edit-config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/maven/MavenSettingsConfig/show-config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/maven/security/ServerCredentialMapping/config.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/properties/security/PropertiesCredentialMapping/config.jelly
Labels: enhancement
