Repository jenkinsci/config-file-provider-plugin, pull requests merged in 2022-01, with the labels that each got.

#169 Bump (together) minimum release, parent pom, and bom
  pom.xml
Labels: dependencies

#167 Remove Github Action maven builds
  .github/workflows/maven.yml
Labels: removed

#168 ignore VScode configuration files (git)
  .gitignore
Labels: chore

#146 [JENKINS-66708] Prepare removal of sunset icons from core
  src/main/resources/lib/configfiles/configfiles.jelly
  src/main/resources/lib/configfiles/providerlist.jelly
  src/main/resources/lib/configfiles/sitepanel.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/configfiles.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/edit.jelly
  src/main/resources/org/jenkinsci/plugins/configfiles/ConfigFilesUI/selectprovider.jelly
  src/main/webapp/images/mvn_s.png
  src/main/webapp/images/mvn_s.svg
Labels: enhancement
